[package]
name = "fuzzy_trie_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "fuzzy_trie_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
fuzzy_trie = "1.2.0"
