name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.13.4'
              otp: '25'
            lint: lint
          - pair:
              elixir: '1.13.4'
              otp: '24'
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install minimal stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: FUZZY_TRIE_FORCE_BUILD=1 mix deps.compile

      - run: FUZZY_TRIE_FORCE_BUILD=1 mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: FUZZY_TRIE_FORCE_BUILD=1 mix test
